fluxion/decoders/gstreamer.py
I have compiled the GStreamer 1.0 codecs for H.264 and H.265. The check seems to work :+1:
=> Add check_run() for GStreamer decoders

.pylintrc, fluxion/codec.py, fluxion/decoder.py, fluxion/decoders/gstreamer.py, fluxion/decoders/h264_jct_vt.py, fluxion/decoders/h265_jct_vt.py, fluxion/fluxion.py, fluxion/main.py, fluxion/test.py, fluxion/test_suite.py, test_suites/dummy/dummy.json
Parallelize by default all tests except those that need hardware acceleration.
=> Parallelize test run

fluster/decoders/gstreamer.py
Support avdec_h264 GStreamer decoder
=> decoders: Add GStreamer-H.264-Libav-Gst1.0

fluster/fluster.py
Add the name of decoders and total tests passed both at the beginning and at the end of the table.
Apart from that, add extra line to separate before and after the name of the test vectors.
=> Improve summary to be easier to read

fluster/decoders/gstreamer.py
Support all stream-formats and alignement combinations
Issue: OCP-1760
=> decoders: Add hev1 and hvc1 decoder

fluster/decoder.py, fluster/decoders/dummy.py, fluster/decoders/ffmpeg.py, fluster/decoders/gstreamer.py, fluster/decoders/h264_jct_vt.py, fluster/decoders/h265_jct_vt.py, fluster/fluster.py, fluster/test.py, fluster/test_suite.py, fluster/test_vector.py
Now
```
|Test|FFmpeg-H.265|
|-|-|
|TOTAL|5/10|
|-|-|
|AMP_A_Samsung_7|☠|
|AMP_B_Samsung_7|✔️|
|AMP_D_Hisilicon_3|⌛|
|AMP_E_Hisilicon_3|⌛|
|AMP_F_Hisilicon_3|⌛|
|AMVP_A_MTK_4|✔️|
|AMVP_B_MTK_4|✔️|
|AMVP_C_Samsung_7|✔️|
|BUMPING_A_ericsson_1|❌|
|CAINIT_A_SHARP_4|✔️|
|-|-|
|Test|FFmpeg-H.265|
|TOTAL|5/10|
```
Before
```
|Test|FFmpeg-H.265|
|-|-|
|TOTAL|5/10|
|-|-|
|AMP_A_Samsung_7|❌|
|AMP_B_Samsung_7|✔️|
|AMP_D_Hisilicon_3|❌|
|AMP_E_Hisilicon_3|❌|
|AMP_F_Hisilicon_3|❌|
|AMVP_A_MTK_4|✔️|
|AMVP_B_MTK_4|✔️|
|AMVP_C_Samsung_7|✔️|
|BUMPING_A_ericsson_1|❌|
|CAINIT_A_SHARP_4|✔️|
|-|-|
|Test|FFmpeg-H.265|
|TOTAL|5/10|
```
=> Differentiate success, failure, timeout and exception

fluster/decoders/ffmpeg.py, fluster/decoders/gstreamer.py
This PR contains VP9 support for GStreamer with V4L2 Stateless, VAAPI, new VA and libvpx support.
=> GStreamer VP9 support and small enhancement

fluster/test_suite.py, fluster/utils.py, requirements.txt
Error fixed:
R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
=> Update pylint to 2.8

fluster/test_suite.py
Consolidate report when running with 1 or multiple jobs.
Remove sequential run because it is not needed anymore.
Before
```
./fluster.py run -d JCT-VT-H.264 -j1
****************************************************************************************************
Running test suite JVT-AVC_V1 with decoder JCT-VT-H.264
Using 1 parallel job(s)
****************************************************************************************************
AUD_MW_E (JCT-VT-H.264.JVT-AVC_V1) ... ok
BA1_FT_C (JCT-VT-H.264.JVT-AVC_V1) ... ok
BA1_Sony_D (JCT-VT-H.264.JVT-AVC_V1) ... ok
BA2_Sony_F (JCT-VT-H.264.JVT-AVC_V1) ... ok
```
Now
```
./fluster.py run -d JCT-VT-H.264 -j1
****************************************************************************************************
Running test suite JVT-AVC_V1 with …
```
=> Improve parallel test report while running

.pylintrc, Makefile, check/H265.json, fluster/codec.py, fluster/decoder.py, fluster/decoders/dummy.py, fluster/decoders/fdk_aac.py, fluster/decoders/ffmpeg.py, fluster/decoders/gstreamer.py, fluster/decoders/h264_jct_vt.py, fluster/decoders/h265_jct_vt.py, fluster/decoders/libvpx.py, fluster/fluster.py, fluster/test.py, fluster/test_suite.py, fluster/test_vector.py, scripts/gen_jct_vc.py, test_suites/aac/ISO_IEC_13818-4_2004.json, test_suites/aac/ISO_IEC_14496-26_2010.json
AAC conformance test suites + necessary changes and tiny refactoring.
I don't understand why it has 3 commits, it should be 2. I rebased from master 4 times.
I also see changes that i had done in OCP-2317 appear here again, although that branch was merged to master :S.
=> OCP-2316 OCP-2351

fluster/test_suite.py
Until now, only the test vectors were properly aligned.
However, neither test suite name or decoder name were,
which made everything look very ugly with long names.
Now, everything is properly aligned to ease human eyes
to process information :)
=> OCP-2365 Add proper alignment for test report

fluster/codec.py, fluster/decoders/av1_aom.py, scripts/gen_av1_aom.py, test_suites/av1/AV1-TEST-VECTORS.json
Add AV1 reference decoder and test vectors from libaom
=> Add AV1 reference decoder and test vectors

fluster/decoders/gstreamer.py
We already have a lot of the stateless decoders, this is a first batch that I tested on upcoming Amphion driver for NXP iMX8QXP.
=> Add VP8, H.264 and H.265 V4L2 Stateful decoder support

fluster/decoders/gstreamer.py
This adds support for V4L2Codecs AV1 V4L2 Stateless decoder. (i.e. v4l2slav1dec)
=> Add support for V4L2Codecs AV1 decoder

check/VP8.json, test_suites/vp8/VP8-TEST-VECTORS.json
From `master` branch to `main` branch.
=> Update vp8-test-vectors URLs

fluster/decoders/gstreamer.py
d3d11av1dec element was added in 1.20 development cycle
=> gstreamer: Add D3D11 AV1 decoder

fluster/fluster.py
When more than one suite is run, only the results from the last suite
are reported in the summary output file. Gather the results for all
the test suites before generating the summary.
Signed-off-by: Laura Nao <laura.nao@collabora.com>
=> Fix summary file when running multiple suites

test_suites/av1/AV1-TEST-VECTORS.json, test_suites/av1/CHROMIUM-10bit-AV1-TEST-VECTORS.json
Correct output formats to 10bits YUV
=> Update AV1 10bits test suites

fluster.py, fluster/main.py, pyproject.toml
Add a pyproject definition compatible with setuputils to allow easier distribution of the project.
=> Add pyproject.toml

pyproject.toml
pyproject.toml
* made modifications to reflect the current state of the project
* added info relevant to python package build ahead of publishing
=> COM-5522: Release Fluster v0.1 in Github

fluster/decoders/ffmpeg.py
Right now it's possible to test FFmpeg Vulkan decoding by using https://github.com/cyanreg/FFmpeg.git branch vulkan
It's required to process frames in vulkan output and then download them in it's native format, to later convert them to the required format for validation.
It requires the latest Vulkan beta driver from NVIDIA or radv/anv drivers from MESA (current top of tree).
=> Add FFMPEG Vulkan decoder for H264 and H265

fluster/decoders/gstreamer.py
[Results](https://gist.github.com/cadubentzen/ba28cc807d9a970128f41d4da8da5a6e)
=> Add GStreamer-based dav1d decoder

fluster/decoders/gstreamer.py
With an initial GStreamer Vulkan H.265 decoder merged https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/6089 we now need to test it :)
=> Add GStreamer Vulkan H265 decoder

fluster/decoders/gstreamer.py, scripts/gen_av1_chromium.py, scripts/gen_jct_vc.py
* gstreamer: fix issue with audio decoders (important!)
* scripts: fix f-string without any placeholders
* scripts: fix imported but unused
=> Some fixes

fluster/decoders/gstreamer.py
Functional testing with fluster (vvcdec)
=> CS-2376-Functional testing with fluster (vvcdec)

.github/workflows/python-app.yml, .github/workflows/release.yml
* add first try in release.yml (without `flu-plugins` testing)
=> COM-12579-Create CI workflow for automated fluster releases (without flu-plugins testing)

.github/workflows/release.yml
fix in adding changelog as notes (include echo -e to file.txt) to avoid special characters issues
=> COM-12579-2-fix in adding changelog as notes

README.md
Set absolute links for PyPI Website navigation after publishing a new release
=> COM-12826-Set absolute links for PyPI Website navigation

fluster/decoders/gstreamer.py
[Results](https://gist.github.com/cadubentzen/6fe8b84dd16d2474272fc0507d2bc407) with [this MR](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/8662)
=> feat: add vah266dec gstreamer decoder

check/dummy.json, fluster/codec.py, fluster/decoders/ffmpeg.py, fluster/test_suite.py, fluster/utils.py, scripts/gen_mpeg4_video.py, test_suites/mpeg4v/MPEG4_VIDEO-SimpleProfile.json
Commands to test:
```
./scripts/gen_mpeg4_video.py
./fluster.py download MPEG4_VIDEO-SimpleProfile
./fluster.py run -ts MPEG4_VIDEO-SimpleProfile -d FFmpeg-MPEG4_VIDEO
```
=> COM-13302 - Create mpeg4 video test suite generator script and test suite for simple profile

fluster/codec.py, scripts/gen_mpeg4_video.py, test_suites/mpeg4v/MPEG4_VIDEO-SimpleScalableProfile.json
./scripts/gen_mpeg4_video.py
./fluster.py download MPEG4_VIDEO-SimpleScalableProfile
./fluster.py run -ts MPEG4_VIDEO-SimpleScalableProfile -d FFmpeg-MPEG4_VIDEO
=> COM-13307 - Adapt mpeg4 video test suite generator script and create test suite for simple scalable profile

fluster/fluster.py
Add cumulative tables for general and per profile pass stats among all executed test suites
=> COM-13300 - Add cumulative tables for general and per profile
