fluendo/fluster

- fluster/decoders/gstreamer.py
The `videoconvert` element is necessary because I420 is not supported by msdk plugins.
msdkh264dec src formats:
```
Capabilities:
video/x-raw
format: NV12
width: [ 1, 2147483647 ]
height: [ 1, 2147483647 ]
framerate: [ 0/1, 2147483647/1 ]
interlace-mode: progressive
video/x-raw(memory:DMABuf)
format: NV12
width: [ 1, 2147483647 ]
height: [ 1, 2147483647 ]
framerate: [ 0/1, 2147483647/1 ]
interlace-mode: progressive
```
msdkh265dec src formats:
```
Capabilities:
video/x-raw
format: { (string)NV12, (string)P010_10LE, (string)YUY2, (string)Y210, (string)VUYA, (string)Y410, (string)P012_LE, (string)Y212_LE, (string)Y412_LE }
width: [ 1, 2147483647 ]
height: [ 1, 2147483647 ]
framerate: [ 0/1, 2147483647/1 ]
interlace-mode: progressive
video/x-raw(memory:DMABuf)
format: { (string)NV12, …
```
> Add GStreamer-H.265-MSDK-Gst1.0 and GStreamer-H.264-MSDK-Gst1.0

- fluster/decoders/gstreamer.py
This reverts commit 056d47884e4fe0a75bd0c0d610d3655125653752.
There is no need to ignore anymore the exit code since the
Windows decoder already works correctly.
> Revert "Ignore exit code of decoders on Windows"

- fluster/test_suite.py
In order to avoid wasting too much disk space, we still remove the files if no keep_files argument is given.
[![asciicast](https://asciinema.org/a/zh5k0FGjyBcTVbWVoyaLJIm6E.svg)](https://asciinema.org/a/zh5k0FGjyBcTVbWVoyaLJIm6E)
> Reuse existing downloaded files if checksum is the same

- README.md
- fluster/decoders/gstreamer.py
- fluster/test_suite.py
This plugin is under development but in the long term aims to replace gstreamer-vaapi. It uses the private library libgstcodecs share among other accelerator API in order to implement VA decoders. This add two new decoders:
p.s. I have also removed the hack preventing to use multiple jobs for HW decoder, let me know if you prefer are separate PR to discuss this. The hack makes it impossible to change the number of jobs and have no practical justification. It does slow down the testing process.
> Add VA plugin from gst-plugins-bad

- Makefile
- README.md
- fluster/fluster.py
- fluster/main.py
Before
```
./fluster.py run -d dummy -ts dummy -th 2 -s
****************************************************************************************************
Running test suite dummy with decoder Dummy
Using 8 parallel job(s)
****************************************************************************************************
.
Ran 1/1 tests successfully in 0.001 secs
Tests results below threshold: 1 vs 2.0
Reporting error through exit code 2
```
Now
```
./fluster.py run -d dummy -ts dummy -th 2 -s
****************************************************************************************************
Running test suite dummy with decoder Dummy
Using 8 parallel job(s)
****************************************************************************************************
.
Ran 1/1 tests …
```
> Show summary in case of threshold failure

- Makefile
- fluster/fluster.py
- fluster/main.py
```./fluster.py run -ts h265short -d FFmpeg-H.265 -s -t 2```
|Test|FFmpeg-H.265|
|-|-|
|TOTAL|4/10|
|-|-|
|AMP_A_Samsung_7|⌛|
|AMP_B_Samsung_7|⌛|
|AMP_D_Hisilicon_3|⌛|
|AMP_E_Hisilicon_3|⌛|
|AMP_F_Hisilicon_3|⌛|
|AMVP_A_MTK_4|✔️|
|AMVP_B_MTK_4|✔️|
|AMVP_C_Samsung_7|✔️|
|BUMPING_A_ericsson_1|❌|
|CAINIT_A_SHARP_4|✔️|
|-|-|
|Test|FFmpeg-H.265|
|TOTAL|4/10|
```./fluster.py -ne run -ts h265short -d FFmpeg-H.265 -s -t 2```
|Test|FFmpeg-H.265|
|-|-|
|TOTAL|7/10|
|-|-|
|AMP_A_Samsung_7|OK️|
|AMP_B_Samsung_7|OK️|
|AMP_D_Hisilicon_3|TO|
|AMP_E_Hisilicon_3|OK️|
|AMP_F_Hisilicon_3|TO|
|AMVP_A_MTK_4|OK️|
|AMVP_B_MTK_4|OK️|
|AMVP_C_Samsung_7|OK️|
|BUMPING_A_ericsson_1|KO|
|CAINIT_A_SHARP_4|OK️|
|-|-|
|Test|FFmpeg-H.265|
|TOTAL|7/10|
> Add --no-emoji option to report in plain text

- fluster/decoders/gstreamer.py
These are new GStreamer decoders for the V4L2 stateless decoders being
worked on in the Linux kernel. These decoders are found on i.MX8M
series, Rockchip, Allwinner, newer Mediatek, Blaize and more SoC.
---
I'll be adding the statefull one soon when I get time to actually test it.
> gst: Add V4L2 stateless decoder support

- fluster/codec.py
- fluster/decoders/ffmpeg.py
- fluster/decoders/gstreamer.py
- fluster/decoders/libvpx.py
- test_suites/vp8/VP8-TEST-VECTORS.json
Current local results:
```
|Test|FFmpeg-VP8|FFmpeg-VP8-VAAPI|GStreamer-VP8-VAAPI-Gst1.0|GStreamer-VP8-libvpx-Gst1.0|
|TOTAL|44/61|39/61|57/61|57/61|
```
Test vectors from https://github.com/webmproject/vp8-test-vectors
Result hash from `vpxdec` tool.
JSON generated with:
```
set -eu
rm -rf templales/*out
echo '
{
"name": "__NAME__",
"source": "https://github.com/webmproject/vp8-test-vectors/raw/master/__NAME__.ivf",
"source_checksum": "__NAMEMD5__",
"input_file": "__NAME__.ivf",
"output_format": "yuv420p",
"result": "__NAMEMD5OUT__"
},
' > template
for in_file in $(ls *.ivf)
do
echo ${in_file}
in_file=${in_file%.ivf}
echo ${in_file}
sed "s/__NAME__/${in_file}/" template > "templates/${in_file}.out"
NAMEMD5=`md5sum ${in_file}.ivf | awk '{ print $1 }'`
sed -i "s/__NAMEMD5__/${NAMEMD5}/" …
```
> Add VP8-TEST-VECTORS (fix #57)

- fluster/codec.py
- fluster/decoders/ffmpeg.py
- fluster/decoders/libvpx.py
- test_suites/vp9/VP9-TEST-VECTORS.json
Hi All,
I would like to add a VP9 test suite. For that being possible VP9 fluster decoders should start existing in the first place. I have created a branch which contains a proposal of how this can be done (both the decoders and the test suite). If you consider my changes fit for merging, kindly do so, If you see other approaches to landing VP9 support that's absolutely fine, too.
I have factored out a base class from vp8 reference decoder and then subclassed it for VP9, adding VP9 test vectors, which come from https://storage.googleapis.com/downloads.webmproject.org/test_data/libvpx/. Please see the corresponding commit message to know how I generated the json. In the last patch I added a VP9 ffmpeg software decoder next to its VP8 counterpart.
> Add VP9 support

- fluster/decoders/gstreamer.py
Add V4L2 stateless VP8 decoder to the list.
Signed-off-by: Benjamin Gaignard <benjamin.gaignard@collabora.com>
> Add v4l2slvp8dec decoder

- fluster/main.py
Before the change:
```
./fluster.py download
usage: fluster.py download [-h] [-j JOBS] [-k] testsuites [testsuites ...]
fluster.py download: error: the following arguments are required: testsuites
```
After change all test suites are downloaded.
Bug added in: https://github.com/fluendo/fluster/commit/28abe738f0ee20798d98027a52e590ea87322a1f#diff-32f2af3ad7194c5108dd8d6d7d308e9a3c4d8fa7f2483280a30f545d74e8eefdR152
Fix: Issue #63
> Download all the test suites when no argument

- Makefile
- check/dummy_download_fail.json
- check/dummy_fail.json
- fluster/codec.py
- fluster/decoders/dummy.py
- fluster/fluster.py
- fluster/main.py
- fluster/test.py
- fluster/test_suite.py
- fluster/test_vector.py
- scripts/gen_jct_vc.py
Consolidate test cases and decoders check for matches
./fluster.py -tsd check download dummy non_existing_test_suite
was not failing before while it does now. We'd rather be
explicit reporting to the user both an error and the test
suite that did not match any available.
This fixes https://github.com/fluendo/fluster/issues/63
> Consolidate test cases and decoders check for matches

- check/dummy_download_fail.json
- check/dummy_fail.json
- fluster/test.py
- fluster/utils.py
Apparently, having 'fail' in the test name has the following
result:
Traceback (most recent call last):
File "/home/pablo/Fluendo/fluster/fluster/test.py", line 73, in _test
self.assertEqual(self.test_vector.result.lower(), result.lower(),
File "/usr/lib/python3.8/unittest/case.py", line 912, in assertEqual
assertion_func(first, second, msg=msg)
File "/usr/lib/python3.8/unittest/case.py", line 1292, in assertMultiLineEqual
self.fail(self._formatMessage(msg, standardMsg))
TypeError: _test() takes 1 positional argument but 2 were given
Most likely this is due to some hidden witchcraft thingy done on
Python's unit test framework. We set the test name by doing:
setattr(self, test_vector.name, self._test)
super().__init__(test_vector.name)
> Fix dummy_fail test vector

- fluster/decoders/gstreamer.py
Add support for GStreamer d3d11vp8dec, d3d11vp9dec, avdec_vp8 and avdec_vp9
elements
> gstreamer: Add D3D11 and Libav VP8/VP9 decoders

- fluster/utils.py
Before:
```
subprocess.TimeoutExpired: Command '['gst-launch-1.0', 'filesrc', 'location=resources/JVT-AVC_V1/MR3_TANDBERG_B/MR3_TANDBERG_B.264', '!', 'h264parse', '!', 'fluvadec', '!', 'video/x-raw', '!', 'videoconvert', 'dither=none', '!', 'video/x-raw,format=I420', '!', 'filesink', 'location=results/JVT-AVC_V1/MR3_TANDBERG_B.yuv']' timed out after 30 seconds
```
After:
```
subprocess.CalledProcessError: Command 'gst-launch-1.0 filesrc location=resources/JVT-AVC_V1/sp2_bt_b/H26L/BitstreamExchange/sp2_bt_b.h264 ! h264parse ! fluvadec ! video/x-raw ! videoconvert dither=none ! video/x-raw,format=I420 ! filesink location=results/JVT-AVC_V1/sp2_bt_b.yuv' returned non-zero exit status 1.
```
> Developer experience improvement to facilitate copy/paste.

- fluster/fluster.py
- fluster/main.py
Whenever I created a sub-test suite from another I forget to change the name and realize about the mistake is not easy. This warning can help.
> Warning if repeated test suite's name

- fluster/decoders/gstreamer.py
This PR is in preparation for GStreamer 1.20 and the new videoconformancesink being accepted. This is sent early, so this can get more attention and testing. The patch will check GStreamer version and use the conformance sink if GStreamer is new enough. With the new videoconformancesink, GStreamer padding is ignored, that padding was breaking some V8 and VP9 tests.
Pending GStremaer MR: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/2287
> Add support for videoconformancesink

- fluster/decoders/gstreamer.py
To execute binary, full name with file extension is required.
cc @ndufresne
> gstreamer: Fix element detection on Windows

- Makefile
- fluster/codec.py
- fluster/decoders/fdk_aac.py
+decoder.py: modified decoder() function argument sequence
+aac_dec.py: added a wrapper for the reference aac decoder
+Makefile: changed target names to be more precise and
replaced 2 targets which were not building executables/files
with variables that can be executed at runtime.
> OCP-2317 : Add AAC reference decoder

- fluster/main.py
- fluster/test_suite.py
We were wrongly assuming when this code was created
that only compressed files would be used. After adding
VP8, VP9 and in the near future the AAC tests, this is
not true anymore.
Before. Starting with an empty resources dir:
```bash
$./fluster.py download VP8-TEST-VECTORS
...
All downloads finished
find resources/VP8-TEST-VECTORS -type f | wc -l
61
./fluster.py download VP8-TEST-VECTORS
...
All downloads finished
find resources/VP8-TEST-VECTORS -type f | wc -l
0
```
Now. Starting with an empty resources dir:
```
$./fluster.py download VP8-TEST-VECTORS
...
All downloads finished
find resources/VP8-TEST-VECTORS -type f | wc -l
61
./fluster.py download VP8-TEST-VECTORS
Downloading test suite VP8-TEST-VECTORS using 16 parallel jobs
All downloads finished
find resources/VP8-TEST-VECTORS -type …
```
> OCP-2337 Fix removing non-compressed downloaded files

- .github/workflows/python-app.yml
- README.md
- fluster/decoder.py
- fluster/test_suite.py
- fluster/test_vector.py
Postponed Evaluation of Annotations (PEP 563) was added in python 3.7 importing annotations from `__future__`.
This commit will have to be reverted when the end of python 3.6 support.
> Bring back support for Python 3.6+ in Fluster

- Makefile
- fluster/decoders/iso_mpeg4_aac.py
- test_suites/aac/ISO_IEC_13818-4_2004.json
- test_suites/aac/ISO_IEC_14496-26_2010.json
Makefile
~ modified aac_reference_decoder target to correspond to steps needed
to build ISO MPEG4 AAC decoder
+ added new "clean" target to be able to delete all content of ./contrib folder
~ refactored other targets to use logical OR "||" instead of pipe operation "|"
to "true"
renamed fdk-aac.py to iso_mpeg4_aac.py
ISO_IEC_13818-4_2004, ISO_IEC_14496-26_2010
~ moved previously failing test vectors into test vector section because they
pass with ISO decoder
+ replaced and added "result" md5 checksums of all test vectors to correspond to the
ISO decoder
> OCP-2399 - Replaced Fraunhofer AAC ref decoder with ISO reference decoder

- fluster/decoders/gstreamer.py
Add VP8 and VP9 nvdec elements, and nv*sldec as well. Note that
nv*sldec elements are new NVDEC implementation based on gstcodecs
> gstreamer: Add support for more NVDEC elements

- fluster/fluster.py
Add a new row to the summary including the total time taken to execute the test suite for each decoder.
The only catch here is what to do with timeouts. I decided to substract the time spent in test vectors that end up in timeout. This way, we are not always comparing the same amount of test vectors decoded, but at least we're not poisoning the results if 1 or more test vectors give timeout.
e.g.
```
./fluster.py run -d FFmpeg-H.264 FFmpeg-H.264-VAAPI GStreamer-H.264-VAAPI-Gst1.0 -j1 -s
```
|Test|FFmpeg-H.264|FFmpeg-H.264-VAAPI|GStreamer-H.264-VAAPI-Gst1.0|
|-|-|-|-|
|TOTAL|120/135|120/135|121/135|
|TOTAL TIME|17.801s|26.751s|36.319s|
|-|-|-|-|
|AUD_MW_E|✔️|✔️|✔️|
|BA1_FT_C|✔️|✔️|✔️|
|BA1_Sony_D|✔️|✔️|✔️|
|BA2_Sony_F|✔️|✔️|✔️|
|BA3_SVA_C|✔️|✔️|✔️|
|BA_MW_D|✔️|✔️|✔️|
|BAMQ1_JVC_C|✔️|✔️|✔️| …
> OCP-2433 Add time spent running a test suite to the summary

- Makefile
- fluster/codec.py
- fluster/decoders/h266_vvdec.py
- fluster/test_suite.py
- scripts/gen_jct_vc.py
- test_suites/h266/JCT-VC-HEVC-V1.json
Origin:
* repo: https://github.com/fraunhoferhhi/vvdec
* commit: ecdd16579413dc3a3298f689ee30ae1a6f3edd41
The test suite is a draft7 and the test vector list is inside the file
`cmake/modules/define_bitstream_files.cmake`.
The Fraunhofer Versatile Video Decoder (VVdC) is in development and
not all the bitstreams from the conformance set that are supported.
> Add H.266 (VTT) test suite and VVdeC reference decoder

- fluster/test_suite.py
If the user, by mistake, uses -tv instead of -ts fluster doesn't
execute any test but doesn't complain either.
Example
```
$ ./fluster.py run -d FFmpeg-H.264 -tv JVT-AVC_V1
$ echo $?
1
```
After change:
```
$ ./fluster.py run -d FFmpeg-H.264 -tv JVT-AVC_V1
No test vectors for suite JVT-AVC_V1 with names: jvt-avc_v1
$ echo $?
1
```
Note: I don't usually confuse arguments, it's for a friend.
> Warning if not test vectors

- .pylintrc
Increase the line limit for duplicate-code with min-similarity-lines
of 20
Fixes issue with last commit:
```
pylint fluster --fail-under=10
************* Module fluster.decoders.gstreamer
fluster/decoders/gstreamer.py:1:0: R0801: Similar lines in 2 files
==fluster.decoders.av1_aom:33
==fluster.decoders.libvpx:38
def decode(
self,
input_filepath: str,
output_filepath: str,
output_format: OutputFormat,
timeout: int,
verbose: bool,
) -> str:
"""Decodes input_filepath in output_filepath"""
run_command(
[self.binary, "--i420", input_filepath, "-o", output_filepath],
timeout=timeout,
verbose=verbose,
)
return file_checksum(output_filepath) (duplicate-code)
-----------------------------------
Your code has been rated at 9.99/10
```
> pylint: Set min-similarity-lines to 20

- README.md
- fluster/fluster.py
- fluster/main.py
Add support for formatting the summary output in JUnit XML format.
Add -f/--format option to specify the format for the summary.
Markdown is selected by default.
Signed-off-by: Laura Nao <laura.nao@collabora.com>
> Add support for generating JUnit XML summary

- README.md
- fluster/fluster.py
- fluster/main.py
- test_suites/av1/AV1-TEST-VECTORS.json
- test_suites/av1/CHROMIUM-10bit-AV1-TEST-VECTORS.json
Add support for formatting the summary output in CSV format.
This feature is useful to create or append to spreadsheets, that contain the test results from different devices or corresponding to different states of a code base.
---
During the development of this patch, I played around with two approaches:
- Using pandas
- Create the CSV manually
My choice for the later boils down to three things:
- Adding pandas introduces a new and quite large dependency
- The pandas library is unable to create CSV files with Multi-column dataframes without the following side effect:
dataframe (containing 3 levels of columns with **a** connected to **c**, **c** connected to **f &g**; **b** connected to **d & e**, **d** connected to **h & i**, **e** connected to **j**:
```
a,,b,,,
c,,d,,e,
f,g,h,i,j,
``` …
> Add support for generating CSV summaries

- fluster/decoder.py
- fluster/decoders/av1_aom.py
- fluster/decoders/chromium.py
- fluster/decoders/dummy.py
- fluster/decoders/ffmpeg.py
- fluster/decoders/gstreamer.py
- fluster/decoders/h264_jct_vt.py
- fluster/decoders/h265_jct_vt.py
- fluster/decoders/h266_vvdec.py
- fluster/decoders/iso_mpeg4_aac.py
- fluster/decoders/libvpx.py
- fluster/test.py
When videocodectestsink is used, the MD5 sum can be computed directly by that sink without writing the image to disk. This improves slightly the test speed, specially with slow rootfs like some SD cards and NFS. This is currently only implemented for GStreamer, though other decoder have this capability. The file will be written to disk if the -k option is passed.
> gstreamer: Avoid writing back raw image file to disk

- fluster/decoders/gstreamer.py
- fluster/utils.py
This is a follow up over the write-less addition. These changes address some left over comment and makes the result behave
close to the previous call to run_command.
TODO:
> Various GStreamer decoder fix and improvement

- fluster/decoders/ffmpeg.py
Add FFMPEG v4l2 m2m stateful support for VP8, VP9 and H264. This uses the decoder wrapper rather than hwaccel.
> Add FFMPEG V4L2 stateful M2M decoder for VP8, VP9 and H264

- test_suites/h264/JVT-FR-EXT.json
This suite covers H.264 10bit and 422 conformance testing. This allow testing higher quality and bitdepth whenever this is supported by the decoder. Note that JM reference decoders may need a bit more then 30s to decoder some of the streams.
> Add JVT Fidelity Range Extensions tests

- fluster/codec.py
- fluster/decoders/gstreamer.py
- test_suites/h264/JVT-FR-EXT.json
As I completely forgot about the format, when I started debugging some codec I realized I had a lot of false positive. This adds 8bit and 10bit YUV support in FFMPEG and GStreamer, and fixes the output_format in the json file. There was no modification to the checksum. I'll send an MR with the GStreamer support too.
> Fixup for JVT Fidelity Range extension

- README.md
- fluster/main.py
"r" was used as alias for run and reference command. The solution was use "f" for the reference command.
Error:
```
root@5d2dda135e50:/fluster# python ./fluster.py
Traceback (most recent call last):
File "/fluster/./fluster.py", line 25, in <module>
main = Main()
^^^^^^
File "/fluster/fluster/main.py", line 44, in __init__
self.parser = self._create_parser()
^^^^^^^^^^^^^^^^^^^^^
File "/fluster/fluster/main.py", line 115, in _create_parser
self._add_reference_cmd(subparsers)
File "/fluster/fluster/main.py", line 244, in _add_reference_cmd
subparser = subparsers.add_parser(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/argparse.py", line 1188, in add_parser
raise ArgumentError(
argparse.ArgumentError: argument {list,l,run,r,download,d}: conflicting subparser alias: r
```
Fix issue …
> Fix parse argument error with Python 3.11

- .github/workflows/python-app.yml
Latest changes to ubuntu-latest distro (before 20.04, after 22.04) introduced by github to GA broke our CI.
This is a fix that sets 20.04 as our preferred distro version
> COM-5670: Fix GA CI failures due to distro upgrade from Ubuntu 20.04 to 22.04

- fluster/main.py
When distributing the tool, we need to store the the test suites under a system directory. Look for a local test_suites directory first and if it doesn't exist, fallback to looking under the system directory for the test suites.
--
Draft as this won't be great for Windows and is kind-of a bit of a hack. Open to suggestions on how to improve :-)
> Allow test_suites to be stored under a system directory

- fluster/decoders/gstreamer.py
Using the fault handler is not appropriate for automatic testing because it stops the execution waiting for user input.
> OCP-4354 Do not use gst-launch-1.0 fault handler

- fluster/decoders/gstreamer.py
- fluster/utils.py
Due to some internal Python issue, the communicate() timeout no longer seem to work. Fix this by using subprocess.check_output instead. This actually makes the helper function simplier.
> Fix broken timeout with run_pipe_command_with_std_output

- fluster/decoders/gstreamer.py
This is needed to enable Qualcomm decoder testing in KernelCI.
> gstreamer: Add V4L2 stateful VP9 decoder support

- fluster/decoders/gstreamer.py
Adding D3D12 H.264, H.265, VP9 and AV1 decoders
See also
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4161
> gstreamer: Add D3D12 decoders

- fluster/decoders/cros_codecs.py
[Cros-codecs](https://github.com/chromeos/cros-codecs) is a new library for decoding video in Rust. It currently offloads to VA-API for hardware acceleration and supports VP8, VP9, AVC and HEVC.
There is a standalone binary, named ccdec, that can be used by Fluster for the purposes of conformance testing.
Add support for it.
> Add the cros-codecs decoder

- README.md
- fluster/decoders/gstreamer.py
- test_suites/h266/JVET-VVC_draft6.json
This PR adds the GStreamer-based based VVdeC decoder.
gst-vvdec is a GStreamer element that uses VVdeC via Rust bindings.
As of now, it has conformance results (243/282) close to vvdecapp (250/282), with the failures in addition being:
- Grayscale: element and videocodectestsink don't support it yet
- Interlaced: not supported by the element yet
I also fixed the output formats in the h266 test suite. The previous values were not used by the VVdeC decoder, but get used by the GStreamer-based VVdeC decoder. This was causing different checksums.
[Results](https://gist.github.com/cadubentzen/48aacf4ae3b709411c60f3a12f956942)
> Add GStreamer based VVdeC decoder

- fluster/fluster.py
- fluster/main.py
- fluster/test_suite.py
Allow multiple attempts to download an asset
Fix #150
> download: add retries argument

- fluster/decoders/gstreamer.py
GStreamer Vulkan H.264 decoder has hit main branch, so its definition in fluster is a must.
> Add GStreamer Vulkan H264 decoder

- fluster/decoders/gstreamer.py
Some AV1 tests are using matroska container, so forcing IFV parser cause some failures. This fixes:
- av1-1-b8-03-sizedown
- av1-1-b8-03-sizeup
> gst: va: Fix AV1 decoder to use parsebin

- fluster/fluster.py
- fluster/test.py
- fluster/test_vector.py
In gitlab junit reports, the testsuite time is not used to show the complete test time and is shown as 0.0 even if set.
Instead, it shows the sum of each test case time.
This adds each test case time in the junit report.
The sum will not give the actual total time when multiple threads are used, but it can already give an idea of the used time.
> junitxml: Add each vector test time

- README.md
- fluster/fluster.py
- fluster/main.py
- fluster/test.py
- fluster/test_suite.py
- fluster/utils.py
* Use `tempfile.gettempdir()` for temporal results directory:
* before commit results_dir is `__file__ /../results`
* after commit results_dir is `/tmp/fluster_results`
The global argument `output` can be used for custom temporal results dir.
*  Using platform dirs to execute installed fluster.
Checking if fluster is uninstalled with the existence of the '.git' dir.
For installed fluster, the site platform dirs is preferred if exists. If not, user platform dirs will be used, that is, `~/.local/share/fluster` (or `XDG_DATA_HOME`) will be used if `/usr/share/fluster` (or `XDG_DATA_DIRS`) doesn't exist.
Fluster tries to use the platformdirs[1] lib. But if not found, it fallbacks to a simple implementation. The reason is to avoid introducing the first external dependency.
[1] …
> Fluster "installed" version

- .github/workflows/python-app.yml
- .pylintrc
- fluster/decoders/__init__.py
- fluster/decoders/av1_dav1d.py
- fluster/decoders/chromium.py
- fluster/decoders/cros_codecs.py
- fluster/decoders/dummy.py
- fluster/decoders/ffmpeg.py
- fluster/decoders/gstreamer.py
- fluster/decoders/h264_jct_vt.py
- fluster/decoders/h265_jct_vt.py
- fluster/decoders/h266_vvdec.py
- fluster/decoders/iso_mpeg4_aac.py
- requirements.txt
The output of the make check with python 3.11 is different that with python 3.6
Adding a new test more with 3.11 to check with the max and min desp supported.
> CI: check python 3.11

- README.md
- fluster/fluster.py
- fluster/main.py
Allowing multiple directories allows the creation of private test suites. Implemented using OS path separator (`os.pathsep`). For instance, on Linux:
```
python3 ./fluster.py -tsd "/opt/fluster_tsd:/opt/priv_f_tsd" list
```
> test-suites-dir: Allow multiple dirs with OS path separator

- fluster/main.py
This feature was added before implementing the installed/uninstalled flavor in the commit a22f609.  The current installed flavor implementation covers this use case, and it is not needed anymore.
> uninstalled: Drop the usage of platform directories for test suites

- fluster/decoders/ffmpeg.py
Fix issue with Bash Linux terminal does not echo the input characters after running a full test suite.
Thanks to Kerin Millar for the help in the bash list [1]
The issue could be reproduced with
```
from multiprocessing import Pool
from unittest.result import TestResult
from time import perf_counter
import subprocess
jobs=3
failfast=False
timeout=30
verbose=True
tests = [1,2,3]
def run_command(command, verbose = False, check = True, timeout = None):
"""Runs a command"""
sout = subprocess.DEVNULL if not verbose else None
serr = subprocess.DEVNULL if not verbose else None
if verbose:
print(f'\nRunning command "{" ".join(command)}"')
try:
subprocess.run(command, stdout=sout, stderr=serr, check=check, timeout=timeout)
except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as ex: …
```
> ffmpeg: pass -nostdin to not alter the terminal settings to begin with.

- Makefile
CMake based builds for reference decoder follow the schema:
`cmake <bla> && $(MAKE) -C build`
This only works for 'Unix Makefile' generator. This breaks if the user has set CMAKE_GENERATOR by default to something different, e.g. Ninja.
> Explicitly set CMAKE_GENERATOR

- fluster/decoders/gstreamer.py
> H264: add fluendo's LCEVC decoder for H264

- fluster/decoders/gstreamer.py
Fluendo divided their decoders by backend and codec, so where before there were just `fluhwvadec` or `fluhwvah264dec`, now there are `fluhwva{backend}{codec}` (`fluhwvavaapih264dec` for example).
This commit generate the types for this decoders programmatically, to reduce the amount of code required otherwise.
Decoders generated:
```
Fluendo-H.264-DXVA2-Gst1.0: Fluendo H.264 DXVA2 decoder for GStreamer 1.0
Fluendo-H.264-VAAPI-Gst1.0: Fluendo H.264 VAAPI decoder for GStreamer 1.0
Fluendo-H.264-VDA-Gst1.0: Fluendo H.264 VDA decoder for GStreamer 1.0
Fluendo-H.264-VDPAU-Gst1.0: Fluendo H.264 VDPAU decoder for GStreamer 1.0
Fluendo-H.264-VT-Gst1.0: Fluendo H.264 VT decoder for GStreamer 1.0
Fluendo-H.265-byte-stream-au-DXVA2-Gst1.0: Fluendo H.265-byte-stream-au DXVA2 decoder for GStreamer 1.0 …
```
> Add support for new decoders of Fluendo

- fluster/decoders/gstreamer.py
Do not limit VP8 tests to IVF container, use parsebin to be more generic. Add check_decoder_bin to continue to check if vp8 decoders exist or not.
> decoder: gstreamer: VP8: Allow to parse more containers

- fluster/decoders/ffmpeg.py
- fluster/decoders/gstreamer.py
- fluster/utils.py
- scripts/gen_jct_vc.py
This PR include misc improvements and refactorings to simplify building the FFmpeg command line.
- Rename and refactor of `utils.run_pipe_command_with_std_output()`
- Use shared `@lru_cache` for ffmpeg commands used in `check()`
- Fix version detect of `<master>`.`<minor>` releases
- Separate handling of `-hw_output_format` and `-hwaccel_output_format`
- Convert `output_format_to_ffformat()` to `hw_download_mapping` property
- Refactor to build command line in `decode()` using a string list
- Validate and inform what codec to use using `-codec`
- Use `md5` muxer when supported to avoid always having to save output files
- Use single-threaded decoding, `fluster` support running multiple jobs
- Rename V4L2 mem2mem decoders
- Add VDPAU VP9 decoder
- Add CUDA/NVDEC decoders
This was tested …
> FFmpeg: Misc improvements, use MD5 muxer and add CUDA/NVDEC decoders

- fluster/utils.py
- scripts/gen_av1_aom.py
- scripts/gen_av1_chromium.py
- scripts/gen_jct_vc.py
- scripts/gen_jvet.py
- test_suites/h265/JCT-VC-3D-HEVC.json
- test_suites/h266/JVET-VVC_draft6.json
- tweaked utils.find_by_ext()
- added _fill_checksum_h266() in gen_jvet.py
- minor corrections throughout
> COM-10976: Add checksum handling function in H266 test suite generator

- fluster/decoders/ffmpeg.py
Since FFmpeg 7.1, the VVC decoder is no longer marked as experimental.
During the execution of JVET-VVC_draft6, the FFmpeg VVC decoder got a a score of 239/282 (84.75%).
[Results](https://gist.github.com/cadubentzen/538d1063ca039392693c6907975a9fc0)
> Add FFmpeg VVC decoder

- fluster/decoders/vk_video_decoder.py
This backend allows to test vk_video_samples sample app vk-video-dec-test
which demonstrates Vulkan Video decoders including h264, h265 and av1.
The application can be found at:
https://github.com/nvpro-samples/vk_video_samples
> decoder: add vk_video_samples backend

- fluster/test_suite.py
- created new download context class DownloadWorkAV1Argon()
- unified download/extraction logic in function _download_worker_av1_argon()
- download and extraction is done in 1 job to avoid overwrite issues
- reduced download+extraction time from 2 hours to 15 minutes
- refactored download() function
> COM-12459: Optimise AV1 Argon test suite extraction process

- pyproject.toml
- scripts/gen_jvt.py
- test_suites/h264/JVT-FR-EXT.json
- test_suites/h264/JVT-Professional_profiles_V1.json
- test_suites/h264/JVT-SVC_V1.json
- implemented FRExt test suite generator code
- slightly modified json file of FRExt test suite
> COM-12449: Add H264 FRExt test suite generator

- Makefile
fix in mpeg4 reference decoder generation x32 to x64 bits and add mpeg2 reference decoder generation in Makefile
> COM-12460: fix in mpeg4 ref dec and add mpeg2 ref dec

- Makefile
- fluster/decoders/iso_mpeg2_aac.py
- test_suites/aac/MPEG2_AAC-ADIF.json
- test_suites/aac/MPEG2_AAC-ADTS.json
* Include improvements in mpeg reference decoders building
* Add JSON generation from ISO-MPEG2-AAC decoder in "iso_mpeg2_aac.py" file
* Change ""result":" values of MPEG2_AAC-ADIF.json and MPEG2_AAC-ADTS.json, from reference decoder, .pcm files
> COM-12575: Investigate erratic behaviour of AAC audio reference decoders

- .gitattributes
- .github/workflows/release.yml
- Makefile
- Add building of all reference decoders and clean up to release workflow
- Improvements in Makefile (h.265 "ubuntu 24.04" and mpeg2,4)
- Add `.gitattributes` file to remove unused files in the release package generated.
> COM-12579-3-Add building of all reference decoders and clean up to release workflow

- fluster/decoders/ffmpeg.py
When
```
$ ffmpeg -version
ffmpeg version n7.1 Copyright (c) 2000-2024 the FFmpeg developers
```
Error:
```
Traceback (most recent call last):
File "/home/rgonzalez/src/github.com/fluendo/fluster/./fluster.py", line 23, in <module>
fluster_main()
File "/home/rgonzalez/src/github.com/fluendo/fluster/fluster/main.py", line 41, in fluster_main
main.run()
File "/home/rgonzalez/src/github.com/fluendo/fluster/fluster/main.py", line 85, in run
args.func(args, fluster)
File "/home/rgonzalez/src/github.com/fluendo/fluster/fluster/main.py", line 371, in _list_cmd
fluster.list_decoders(check=args.check, verbose=args.verbose)
File "/home/rgonzalez/src/github.com/fluendo/fluster/fluster/fluster.py", line 204, in list_decoders
if decoder.check(verbose)
^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Fix issue with FFmpeg version no patch version

- fluster/decoders/iso_mpeg4_aac.py
- scripts/gen_aac.py
- test_suites/aac/MPEG4_AAC-MP4.json
MPEG-4 AAC mp4
modified:   scripts/gen_aac.py
- Modified Regex for MPEG2_AAC_ADIF
- Different parsers were added, one for each kind of file (compressed, raw and checksum)
- DVD3 Wav files were added
- Validation logic for audio files was added
> COM-12464 - MPEG-4 AAC mp4

- fluster/decoders/gstreamer.py
ARGON AV1 test suite use GBR_10LE as output format, for GStreamer decoders map it to GBR_10LE.
> decoders: gstreamer: Add mapping for GBRP10LE pixel format

- fluster/decoders/ffmpeg.py
- fluster/utils.py
The goal of fluster is to test one specific implementation, allowing software fallback hides possible integration issues.
> ffmpeg: Detect and fail on software decoder fallback

- .github/workflows/python-app.yml
- Makefile
- check/AV1.json
We want to add some basic test suites and tests for AV1 in target check of Makefile
> COM-12617: Add basic AV1 tests for Makefile check target

- fluster/decoders/gstreamer.py
Fix H266 TS output format gray10le32->gray10le16
The proper output format of the decoder is 16b aligned, instead of 32.
> OCP-5946 Fix H266 output format

- README.md
- fluster/decoders/gstreamer.py
- libav mpeg video (avdec_mpeg2video)
- libmpeg mpeg video (mpeg2dec)
> Add some gstreamer mpeg2 video decoders

- fluster/test_suite.py
To select a set of test vectors with a pattern,
use of `fnmatch` on the list of test vectors.
It allows to get a sub list of test vectors, ie:
./fluster.py run -s -d GStreamer-VP9-VA-Gst1.0 -tv vp90-2-12* vp90-2-11*
vp90-2-11-size-351x287.webm|✔️|
|vp90-2-11-size-351x288.webm|✔️|
|vp90-2-11-size-352x287.webm|✔️|
|vp90-2-12-droppable_1.ivf|✔️|
|vp90-2-12-droppable_2.ivf|✔️|
|vp90-2-12-droppable_3.ivf|✔️|
> test_suite: support wildcard in test vector argument

- fluster/decoders/vk_video_decoder.py
Use enablePostProcessFilter by default to support
hardware with different queue for decode and transfer such as mesa drivers.
See https://github.com/KhronosGroup/Vulkan-Video-Samples/issues/57
> fix: vkvs use enablePostProcessFilter

- fluster/test_suite.py
Also print out a message to guide the user on how to download test suites
resolves #232
> Prevent test suites from being executed when their resources are missing

- fluster/decoders/gstreamer.py
Some test suites have test vectors with `"output_format": "None"`.
Rather than failing outright on them, let them run without the format set in the raw caps.
> gstreamer: do not fail when output_format is None

- fluster/decoders/gstreamer.py
- missing formats are GRAY12LE, YUV444P14LE, YUV444P16LE, GBRP, GBRP10LE, GBRP12LE, GBRP14LE
> add missing output formats to GStreamer mapping

- scripts/gen_jvet.py
- scripts/gen_mpeg4_video.py
- test_suites/h.266/JVET-VVC_draft6.json
- test_suites/mpeg4v/MPEG4_VIDEO-SimpleStudioProfile.json
**H.266 test vectors None → yuv420p10le**
seeing downloaded txt files attached in the zip file:
e.g.
The purpose of this bitstream is to test decoding of a bitstream that contains mixed NAL unit types in some of the pictures.
```
Bitstream file:         MNUT_A_Nokia_3.bit
Profile:                Main 10
Tier:                   Main
Level:                  3
Format:                 YUV 420
Picture size:           704x576
Picture rate:           30
CTU size:               32x32
GOP length:             16
Number of pictures:     65
```
**MPEG4 Studio Profile Test Vectors:**
Used FFmpeg to analyze bitstream characteristics and determine bit depth, e.g.:
`ffmpeg -i "vcon-stp12L2" -frames:v 1 test_output.yuv -v verbose 2>&1`
FFmpeg reports specific error messages for 8-bit vs 10-bit Studio …
> Test vectors in suites for MPEG4 video and H.266 have undetermined output format

- fluster/decoders/av1_aom.py
- fluster/fluster.py
- scripts/gen_av1_argon.py
- test_suites/av1/AV1-ARGON-PROFILE0-CORE-ANNEX-B.json
- test_suites/av1/AV1-ARGON-PROFILE0-NON-ANNEX-B.json
- test_suites/av1/AV1-ARGON-PROFILE0-STRESS-ANNEX-B.json
- test_suites/av1/AV1-ARGON-PROFILE1-CORE-ANNEX-B.json
- test_suites/av1/AV1-ARGON-PROFILE1-NON-ANNEX-B.json
- test_suites/av1/AV1-ARGON-PROFILE1-STRESS-ANNEX-B.json
- test_suites/av1/AV1-ARGON-PROFILE2-CORE-ANNEX-B.json
- test_suites/av1/AV1-ARGON-PROFILE2-NON-ANNEX-B.json
- test_suites/av1/AV1-ARGON-PROFILE2-STRESS-ANNEX-B.json
- modify AV1 argon test suite generator to calculate expected md5 checksums using libaom AV1 reference decoder
- remove `multiple_layers` parameter from libaom AV1 decoder
- refactor for multiple OSs
> fix: calculate AV1 Argon checksums based on output of reference decoder
